/*
 * The following words are reserved by PostgreSQL (and thus oughtn't be used as
 * column names or identifiers without being escaped), for more information,
 * see: https://www.postgresql.org/docs/10/static/sql-keywords-appendix.html
 *
 * The data below can be generated and copied to clipboard by running the
 * follow code snippet on the above URL using the Chrome Devtools:

copy(JSON.stringify(Array.prototype.slice.call(document.querySelector("#KEYWORDS-TABLE table tbody").getElementsByTagName("tr")).reduce((memo, tr) => {const tds = tr.getElementsByTagName("td"); const keyword = tds[0].innerText; const status = tds[1].innerText; memo[keyword.toLowerCase()] = status.trim(); return memo;}, {}), null, 2))

 */

const keywords = {
  a: "",
  abort: "non-reserved",
  abs: "",
  absent: "",
  absolute: "non-reserved",
  access: "non-reserved",
  according: "",
  action: "non-reserved",
  ada: "",
  add: "non-reserved",
  admin: "non-reserved",
  after: "non-reserved",
  aggregate: "non-reserved",
  all: "reserved",
  allocate: "",
  also: "non-reserved",
  alter: "non-reserved",
  always: "non-reserved",
  analyse: "reserved",
  analyze: "reserved",
  and: "reserved",
  any: "reserved",
  are: "",
  array: "reserved",
  array_agg: "",
  array_max_cardinality: "",
  as: "reserved",
  asc: "reserved",
  asensitive: "",
  assertion: "non-reserved",
  assignment: "non-reserved",
  asymmetric: "reserved",
  at: "non-reserved",
  atomic: "",
  attach: "non-reserved",
  attribute: "non-reserved",
  attributes: "",
  authorization: "reserved (can be function or type)",
  avg: "",
  backward: "non-reserved",
  base64: "",
  before: "non-reserved",
  begin: "non-reserved",
  begin_frame: "",
  begin_partition: "",
  bernoulli: "",
  between: "non-reserved (cannot be function or type)",
  bigint: "non-reserved (cannot be function or type)",
  binary: "reserved (can be function or type)",
  bit: "non-reserved (cannot be function or type)",
  bit_length: "",
  blob: "",
  blocked: "",
  bom: "",
  boolean: "non-reserved (cannot be function or type)",
  both: "reserved",
  breadth: "",
  by: "non-reserved",
  c: "",
  cache: "non-reserved",
  call: "",
  called: "non-reserved",
  cardinality: "",
  cascade: "non-reserved",
  cascaded: "non-reserved",
  case: "reserved",
  cast: "reserved",
  catalog: "non-reserved",
  catalog_name: "",
  ceil: "",
  ceiling: "",
  chain: "non-reserved",
  char: "non-reserved (cannot be function or type)",
  character: "non-reserved (cannot be function or type)",
  characteristics: "non-reserved",
  characters: "",
  character_length: "",
  character_set_catalog: "",
  character_set_name: "",
  character_set_schema: "",
  char_length: "",
  check: "reserved",
  checkpoint: "non-reserved",
  class: "non-reserved",
  class_origin: "",
  clob: "",
  close: "non-reserved",
  cluster: "non-reserved",
  coalesce: "non-reserved (cannot be function or type)",
  cobol: "",
  collate: "reserved",
  collation: "reserved (can be function or type)",
  collation_catalog: "",
  collation_name: "",
  collation_schema: "",
  collect: "",
  column: "reserved",
  columns: "non-reserved",
  column_name: "",
  command_function: "",
  command_function_code: "",
  comment: "non-reserved",
  comments: "non-reserved",
  commit: "non-reserved",
  committed: "non-reserved",
  concurrently: "reserved (can be function or type)",
  condition: "",
  condition_number: "",
  configuration: "non-reserved",
  conflict: "non-reserved",
  connect: "",
  connection: "non-reserved",
  connection_name: "",
  constraint: "reserved",
  constraints: "non-reserved",
  constraint_catalog: "",
  constraint_name: "",
  constraint_schema: "",
  constructor: "",
  contains: "",
  content: "non-reserved",
  continue: "non-reserved",
  control: "",
  conversion: "non-reserved",
  convert: "",
  copy: "non-reserved",
  corr: "",
  corresponding: "",
  cost: "non-reserved",
  count: "",
  covar_pop: "",
  covar_samp: "",
  create: "reserved",
  cross: "reserved (can be function or type)",
  csv: "non-reserved",
  cube: "non-reserved",
  cume_dist: "",
  current: "non-reserved",
  current_catalog: "reserved",
  current_date: "reserved",
  current_default_transform_group: "",
  current_path: "",
  current_role: "reserved",
  current_row: "",
  current_schema: "reserved (can be function or type)",
  current_time: "reserved",
  current_timestamp: "reserved",
  current_transform_group_for_type: "",
  current_user: "reserved",
  cursor: "non-reserved",
  cursor_name: "",
  cycle: "non-reserved",
  data: "non-reserved",
  database: "non-reserved",
  datalink: "",
  date: "",
  datetime_interval_code: "",
  datetime_interval_precision: "",
  day: "non-reserved",
  db: "",
  deallocate: "non-reserved",
  dec: "non-reserved (cannot be function or type)",
  decimal: "non-reserved (cannot be function or type)",
  declare: "non-reserved",
  default: "reserved",
  defaults: "non-reserved",
  deferrable: "reserved",
  deferred: "non-reserved",
  defined: "",
  definer: "non-reserved",
  degree: "",
  delete: "non-reserved",
  delimiter: "non-reserved",
  delimiters: "non-reserved",
  dense_rank: "",
  depends: "non-reserved",
  depth: "",
  deref: "",
  derived: "",
  desc: "reserved",
  describe: "",
  descriptor: "",
  detach: "non-reserved",
  deterministic: "",
  diagnostics: "",
  dictionary: "non-reserved",
  disable: "non-reserved",
  discard: "non-reserved",
  disconnect: "",
  dispatch: "",
  distinct: "reserved",
  dlnewcopy: "",
  dlpreviouscopy: "",
  dlurlcomplete: "",
  dlurlcompleteonly: "",
  dlurlcompletewrite: "",
  dlurlpath: "",
  dlurlpathonly: "",
  dlurlpathwrite: "",
  dlurlscheme: "",
  dlurlserver: "",
  dlvalue: "",
  do: "reserved",
  document: "non-reserved",
  domain: "non-reserved",
  double: "non-reserved",
  drop: "non-reserved",
  dynamic: "",
  dynamic_function: "",
  dynamic_function_code: "",
  each: "non-reserved",
  element: "",
  else: "reserved",
  empty: "",
  enable: "non-reserved",
  encoding: "non-reserved",
  encrypted: "non-reserved",
  end: "reserved",
  "end-exec": "",
  end_frame: "",
  end_partition: "",
  enforced: "",
  enum: "non-reserved",
  equals: "",
  escape: "non-reserved",
  event: "non-reserved",
  every: "",
  except: "reserved",
  exception: "",
  exclude: "non-reserved",
  excluding: "non-reserved",
  exclusive: "non-reserved",
  exec: "",
  execute: "non-reserved",
  exists: "non-reserved (cannot be function or type)",
  exp: "",
  explain: "non-reserved",
  expression: "",
  extension: "non-reserved",
  external: "non-reserved",
  extract: "non-reserved (cannot be function or type)",
  false: "reserved",
  family: "non-reserved",
  fetch: "reserved",
  file: "",
  filter: "non-reserved",
  final: "",
  first: "non-reserved",
  first_value: "",
  flag: "",
  float: "non-reserved (cannot be function or type)",
  floor: "",
  following: "non-reserved",
  for: "reserved",
  force: "non-reserved",
  foreign: "reserved",
  fortran: "",
  forward: "non-reserved",
  found: "",
  frame_row: "",
  free: "",
  freeze: "reserved (can be function or type)",
  from: "reserved",
  fs: "",
  full: "reserved (can be function or type)",
  function: "non-reserved",
  functions: "non-reserved",
  fusion: "",
  g: "",
  general: "",
  generated: "non-reserved",
  get: "",
  global: "non-reserved",
  go: "",
  goto: "",
  grant: "reserved",
  granted: "non-reserved",
  greatest: "non-reserved (cannot be function or type)",
  group: "reserved",
  grouping: "non-reserved (cannot be function or type)",
  groups: "",
  handler: "non-reserved",
  having: "reserved",
  header: "non-reserved",
  hex: "",
  hierarchy: "",
  hold: "non-reserved",
  hour: "non-reserved",
  id: "",
  identity: "non-reserved",
  if: "non-reserved",
  ignore: "",
  ilike: "reserved (can be function or type)",
  immediate: "non-reserved",
  immediately: "",
  immutable: "non-reserved",
  implementation: "",
  implicit: "non-reserved",
  import: "non-reserved",
  in: "reserved",
  including: "non-reserved",
  increment: "non-reserved",
  indent: "",
  index: "non-reserved",
  indexes: "non-reserved",
  indicator: "",
  inherit: "non-reserved",
  inherits: "non-reserved",
  initially: "reserved",
  inline: "non-reserved",
  inner: "reserved (can be function or type)",
  inout: "non-reserved (cannot be function or type)",
  input: "non-reserved",
  insensitive: "non-reserved",
  insert: "non-reserved",
  instance: "",
  instantiable: "",
  instead: "non-reserved",
  int: "non-reserved (cannot be function or type)",
  integer: "non-reserved (cannot be function or type)",
  integrity: "",
  intersect: "reserved",
  intersection: "",
  interval: "non-reserved (cannot be function or type)",
  into: "reserved",
  invoker: "non-reserved",
  is: "reserved (can be function or type)",
  isnull: "reserved (can be function or type)",
  isolation: "non-reserved",
  join: "reserved (can be function or type)",
  k: "",
  key: "non-reserved",
  key_member: "",
  key_type: "",
  label: "non-reserved",
  lag: "",
  language: "non-reserved",
  large: "non-reserved",
  last: "non-reserved",
  last_value: "",
  lateral: "reserved",
  lead: "",
  leading: "reserved",
  leakproof: "non-reserved",
  least: "non-reserved (cannot be function or type)",
  left: "reserved (can be function or type)",
  length: "",
  level: "non-reserved",
  library: "",
  like: "reserved (can be function or type)",
  like_regex: "",
  limit: "reserved",
  link: "",
  listen: "non-reserved",
  ln: "",
  load: "non-reserved",
  local: "non-reserved",
  localtime: "reserved",
  localtimestamp: "reserved",
  location: "non-reserved",
  locator: "",
  lock: "non-reserved",
  locked: "non-reserved",
  logged: "non-reserved",
  lower: "",
  m: "",
  map: "",
  mapping: "non-reserved",
  match: "non-reserved",
  matched: "",
  materialized: "non-reserved",
  max: "",
  maxvalue: "non-reserved",
  max_cardinality: "",
  member: "",
  merge: "",
  message_length: "",
  message_octet_length: "",
  message_text: "",
  method: "non-reserved",
  min: "",
  minute: "non-reserved",
  minvalue: "non-reserved",
  mod: "",
  mode: "non-reserved",
  modifies: "",
  module: "",
  month: "non-reserved",
  more: "",
  move: "non-reserved",
  multiset: "",
  mumps: "",
  name: "non-reserved",
  names: "non-reserved",
  namespace: "",
  national: "non-reserved (cannot be function or type)",
  natural: "reserved (can be function or type)",
  nchar: "non-reserved (cannot be function or type)",
  nclob: "",
  nesting: "",
  new: "non-reserved",
  next: "non-reserved",
  nfc: "",
  nfd: "",
  nfkc: "",
  nfkd: "",
  nil: "",
  no: "non-reserved",
  none: "non-reserved (cannot be function or type)",
  normalize: "",
  normalized: "",
  not: "reserved",
  nothing: "non-reserved",
  notify: "non-reserved",
  notnull: "reserved (can be function or type)",
  nowait: "non-reserved",
  nth_value: "",
  ntile: "",
  null: "reserved",
  nullable: "",
  nullif: "non-reserved (cannot be function or type)",
  nulls: "non-reserved",
  number: "",
  numeric: "non-reserved (cannot be function or type)",
  object: "non-reserved",
  occurrences_regex: "",
  octets: "",
  octet_length: "",
  of: "non-reserved",
  off: "non-reserved",
  offset: "reserved",
  oids: "non-reserved",
  old: "non-reserved",
  on: "reserved",
  only: "reserved",
  open: "",
  operator: "non-reserved",
  option: "non-reserved",
  options: "non-reserved",
  or: "reserved",
  order: "reserved",
  ordering: "",
  ordinality: "non-reserved",
  others: "",
  out: "non-reserved (cannot be function or type)",
  outer: "reserved (can be function or type)",
  output: "",
  over: "non-reserved",
  overlaps: "reserved (can be function or type)",
  overlay: "non-reserved (cannot be function or type)",
  overriding: "non-reserved",
  owned: "non-reserved",
  owner: "non-reserved",
  p: "",
  pad: "",
  parallel: "non-reserved",
  parameter: "",
  parameter_mode: "",
  parameter_name: "",
  parameter_ordinal_position: "",
  parameter_specific_catalog: "",
  parameter_specific_name: "",
  parameter_specific_schema: "",
  parser: "non-reserved",
  partial: "non-reserved",
  partition: "non-reserved",
  pascal: "",
  passing: "non-reserved",
  passthrough: "",
  password: "non-reserved",
  path: "",
  percent: "",
  percentile_cont: "",
  percentile_disc: "",
  percent_rank: "",
  period: "",
  permission: "",
  placing: "reserved",
  plans: "non-reserved",
  pli: "",
  policy: "non-reserved",
  portion: "",
  position: "non-reserved (cannot be function or type)",
  position_regex: "",
  power: "",
  precedes: "",
  preceding: "non-reserved",
  precision: "non-reserved (cannot be function or type)",
  prepare: "non-reserved",
  prepared: "non-reserved",
  preserve: "non-reserved",
  primary: "reserved",
  prior: "non-reserved",
  privileges: "non-reserved",
  procedural: "non-reserved",
  procedure: "non-reserved",
  program: "non-reserved",
  public: "",
  publication: "non-reserved",
  quote: "non-reserved",
  range: "non-reserved",
  rank: "",
  read: "non-reserved",
  reads: "",
  real: "non-reserved (cannot be function or type)",
  reassign: "non-reserved",
  recheck: "non-reserved",
  recovery: "",
  recursive: "non-reserved",
  ref: "non-reserved",
  references: "reserved",
  referencing: "non-reserved",
  refresh: "non-reserved",
  regr_avgx: "",
  regr_avgy: "",
  regr_count: "",
  regr_intercept: "",
  regr_r2: "",
  regr_slope: "",
  regr_sxx: "",
  regr_sxy: "",
  regr_syy: "",
  reindex: "non-reserved",
  relative: "non-reserved",
  release: "non-reserved",
  rename: "non-reserved",
  repeatable: "non-reserved",
  replace: "non-reserved",
  replica: "non-reserved",
  requiring: "",
  reset: "non-reserved",
  respect: "",
  restart: "non-reserved",
  restore: "",
  restrict: "non-reserved",
  result: "",
  return: "",
  returned_cardinality: "",
  returned_length: "",
  returned_octet_length: "",
  returned_sqlstate: "",
  returning: "reserved",
  returns: "non-reserved",
  revoke: "non-reserved",
  right: "reserved (can be function or type)",
  role: "non-reserved",
  rollback: "non-reserved",
  rollup: "non-reserved",
  routine: "",
  routine_catalog: "",
  routine_name: "",
  routine_schema: "",
  row: "non-reserved (cannot be function or type)",
  rows: "non-reserved",
  row_count: "",
  row_number: "",
  rule: "non-reserved",
  savepoint: "non-reserved",
  scale: "",
  schema: "non-reserved",
  schemas: "non-reserved",
  schema_name: "",
  scope: "",
  scope_catalog: "",
  scope_name: "",
  scope_schema: "",
  scroll: "non-reserved",
  search: "non-reserved",
  second: "non-reserved",
  section: "",
  security: "non-reserved",
  select: "reserved",
  selective: "",
  self: "",
  sensitive: "",
  sequence: "non-reserved",
  sequences: "non-reserved",
  serializable: "non-reserved",
  server: "non-reserved",
  server_name: "",
  session: "non-reserved",
  session_user: "reserved",
  set: "non-reserved",
  setof: "non-reserved (cannot be function or type)",
  sets: "non-reserved",
  share: "non-reserved",
  show: "non-reserved",
  similar: "reserved (can be function or type)",
  simple: "non-reserved",
  size: "",
  skip: "non-reserved",
  smallint: "non-reserved (cannot be function or type)",
  snapshot: "non-reserved",
  some: "reserved",
  source: "",
  space: "",
  specific: "",
  specifictype: "",
  specific_name: "",
  sql: "non-reserved",
  sqlcode: "",
  sqlerror: "",
  sqlexception: "",
  sqlstate: "",
  sqlwarning: "",
  sqrt: "",
  stable: "non-reserved",
  standalone: "non-reserved",
  start: "non-reserved",
  state: "",
  statement: "non-reserved",
  static: "",
  statistics: "non-reserved",
  stddev_pop: "",
  stddev_samp: "",
  stdin: "non-reserved",
  stdout: "non-reserved",
  storage: "non-reserved",
  strict: "non-reserved",
  strip: "non-reserved",
  structure: "",
  style: "",
  subclass_origin: "",
  submultiset: "",
  subscription: "non-reserved",
  substring: "non-reserved (cannot be function or type)",
  substring_regex: "",
  succeeds: "",
  sum: "",
  symmetric: "reserved",
  sysid: "non-reserved",
  system: "non-reserved",
  system_time: "",
  system_user: "",
  t: "",
  table: "reserved",
  tables: "non-reserved",
  tablesample: "reserved (can be function or type)",
  tablespace: "non-reserved",
  table_name: "",
  temp: "non-reserved",
  template: "non-reserved",
  temporary: "non-reserved",
  text: "non-reserved",
  then: "reserved",
  ties: "",
  time: "non-reserved (cannot be function or type)",
  timestamp: "non-reserved (cannot be function or type)",
  timezone_hour: "",
  timezone_minute: "",
  to: "reserved",
  token: "",
  top_level_count: "",
  trailing: "reserved",
  transaction: "non-reserved",
  transactions_committed: "",
  transactions_rolled_back: "",
  transaction_active: "",
  transform: "non-reserved",
  transforms: "",
  translate: "",
  translate_regex: "",
  translation: "",
  treat: "non-reserved (cannot be function or type)",
  trigger: "non-reserved",
  trigger_catalog: "",
  trigger_name: "",
  trigger_schema: "",
  trim: "non-reserved (cannot be function or type)",
  trim_array: "",
  true: "reserved",
  truncate: "non-reserved",
  trusted: "non-reserved",
  type: "non-reserved",
  types: "non-reserved",
  uescape: "",
  unbounded: "non-reserved",
  uncommitted: "non-reserved",
  under: "",
  unencrypted: "non-reserved",
  union: "reserved",
  unique: "reserved",
  unknown: "non-reserved",
  unlink: "",
  unlisten: "non-reserved",
  unlogged: "non-reserved",
  unnamed: "",
  unnest: "",
  until: "non-reserved",
  untyped: "",
  update: "non-reserved",
  upper: "",
  uri: "",
  usage: "",
  user: "reserved",
  user_defined_type_catalog: "",
  user_defined_type_code: "",
  user_defined_type_name: "",
  user_defined_type_schema: "",
  using: "reserved",
  vacuum: "non-reserved",
  valid: "non-reserved",
  validate: "non-reserved",
  validator: "non-reserved",
  value: "non-reserved",
  values: "non-reserved (cannot be function or type)",
  value_of: "",
  varbinary: "",
  varchar: "non-reserved (cannot be function or type)",
  variadic: "reserved",
  varying: "non-reserved",
  var_pop: "",
  var_samp: "",
  verbose: "reserved (can be function or type)",
  version: "non-reserved",
  versioning: "",
  view: "non-reserved",
  views: "non-reserved",
  volatile: "non-reserved",
  when: "reserved",
  whenever: "",
  where: "reserved",
  whitespace: "non-reserved",
  width_bucket: "",
  window: "reserved",
  with: "reserved",
  within: "non-reserved",
  without: "non-reserved",
  work: "non-reserved",
  wrapper: "non-reserved",
  write: "non-reserved",
  xml: "non-reserved",
  xmlagg: "",
  xmlattributes: "non-reserved (cannot be function or type)",
  xmlbinary: "",
  xmlcast: "",
  xmlcomment: "",
  xmlconcat: "non-reserved (cannot be function or type)",
  xmldeclaration: "",
  xmldocument: "",
  xmlelement: "non-reserved (cannot be function or type)",
  xmlexists: "non-reserved (cannot be function or type)",
  xmlforest: "non-reserved (cannot be function or type)",
  xmliterate: "",
  xmlnamespaces: "non-reserved (cannot be function or type)",
  xmlparse: "non-reserved (cannot be function or type)",
  xmlpi: "non-reserved (cannot be function or type)",
  xmlquery: "",
  xmlroot: "non-reserved (cannot be function or type)",
  xmlschema: "",
  xmlserialize: "non-reserved (cannot be function or type)",
  xmltable: "non-reserved (cannot be function or type)",
  xmltext: "",
  xmlvalidate: "",
  year: "non-reserved",
  yes: "non-reserved",
  zone: "non-reserved",
};

export default Object.keys(keywords);
